### ISSUE TITLE
Failed to start josso

### ISSUE THREAD

**Issue by itsliang** [atricore/atricore-josso-playground#1]
When I ran `docker run -d --name josso atricore/josso:josso-ce-2.4.2`, I got this error:

```
atricore: Clearing OSGi plug-ins cache ...
       __ _____ _____ _____ _____    ___    _____ _____
    __|  |     |   __|   __|     |  |_  |  |     |   __|
   |  |  |  |  |__   |__   |  |  |  |  _|  |   --|   __|
   |_____|_____|_____|_____|_____|  |___|  |_____|_____|

  JOSSO 2 CE             (2.4.2)
  Atricore Console CE    (1.3.2) http://localhost:8081/atricore-console/
  Atricore Identity Bus  (1.4.2)

  Update                 (000)

  Build                  (2016-09-10 18:49:55)

  Apache Karaf           (2.2.3)


Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.

Hit '<ctrl-d>' or type 'osgi:shutdown' to shutdown JOSSO 2 CE.

karaf@josso-ce>
ERROR: Bundle org.apache.karaf.deployer.features [31] EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: Can only register services while bundle is active or activating.)
java.lang.IllegalStateException: Can only register services while bundle is active or activating.
    at org.apache.felix.framework.Felix.registerService(Felix.java:2831)
    at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:251)
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.registerService(BlueprintContainerImpl.java:404)
    at org.apache.aries.blueprint.container.ServiceRecipe.register(ServiceRecipe.java:184)
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.notifySatisfaction(BlueprintContainerImpl.java:612)
    at org.apache.aries.blueprint.container.AbstractServiceReferenceRecipe.setSatisfied(AbstractServiceReferenceRecipe.java:305)
    at org.apache.aries.blueprint.container.AbstractServiceReferenceRecipe.serviceAdded(AbstractServiceReferenceRecipe.java:262)
    at org.apache.aries.blueprint.container.AbstractServiceReferenceRecipe.serviceChanged(AbstractServiceReferenceRecipe.java:245)
    at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:871)
    at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:733)
    at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:662)
    at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:3772)
    at org.apache.felix.framework.Felix.access$000(Felix.java:80)
    at org.apache.felix.framework.Felix$2.serviceChanged(Felix.java:729)
    at org.apache.felix.framework.ServiceRegistry.registerService(ServiceRegistry.java:107)
    at org.apache.felix.framework.Felix.registerService(Felix.java:2861)
    at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:251)
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.registerService(BlueprintContainerImpl.java:404)
    at org.apache.aries.blueprint.container.ServiceRecipe.register(ServiceRecipe.java:184)
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.registerServices(BlueprintContainerImpl.java:662)
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:330)
    at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:227)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

OS: OSX 10.11.6
Docker: 1.12.2-rc1-beta27 (build: 12496)

**Comment by gbrigandi** [comment]
Hi, 
Please make sure to include the '-t' flag upon running the JOSSO CE image. This was missing in the documentation and has been just included.
You might also want to run josso in the foreground for accessing it's command line console: 
$ docker run -t -i --name josso atricore/josso:josso-ce-2.4.2

Regards,
Gianluca.
